spring:
  config:
#    This file you can ignore/remove it .
    import: Secrets.yaml

#    Spring Data base configuration un-comment and fill details while using

#  datasource:
#    url: jdbc:postgresql://localhost:5432/Truth-Dare-App
#    username: your-username
#    password: your-password

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Spring Mail Configuration un-comment and fill details while using

#  mail:
#    properties:
#      mail:
#        smtp:
#          starttls:
#            enable: 'true'
#          auth: 'true'
#    host: smtp.gmail.com
#    username:  yourEmail
#    password: yourEmailAppPassword
#    port: '587'

# JWT Secret Key

#secretKey: ""
