spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Truth-Dare-App
    username: postgres
    password: Suryansh@1904
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
